#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Disable annoying autocorrection
unsetopt correct

# fzf keybindings
[[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh

# z
. ~/bin/z/z.sh
